(require 'package)
(add-to-list 'package-archives
	     '("melpa-stable" . "https://stable.melpa.org/packages/"))
(package-initialize)
(unless (package-installed-p 'elpy)
  (package-refresh-contents)
  (package-install 'elpy)
  (shell-command "yes y| pip install --user -U rope jedi flake8 autopep8 yapf &")
  (shell-command "export PATH=${PATH}:~/.local/bin"))
(unless (package-installed-p 'webmode)
  (package-refresh-contents)
  (package-install 'web-mode)
(elpy-enable)
(setq elpy-rpc-python-command "python3")
(global-set-key (kbd "C-c <left>")  'windmove-left)
(global-set-key (kbd "C-c <down>")  'windmove-down)
(global-set-key (kbd "C-c <up>")    'windmove-up)
(global-set-key (kbd "C-c <right>") 'windmove-right)

(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'cyberpunk t)

(add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\'" . web-mode))

